export const ALLOWED_FIELDS_TO_UPDATE = [
  // 'id',
  // 'order_id',
  'phone_number',
  'product_name',
  'product_type',
  'package_register_type',
  'order_status',
  'provider',
  'total_price',
  'commission_agent',
  'commission_sub_agent',
  'agent_id',
  'sub_agent_id',
  // 'date',
  'success_date',
  'cross_check_id',
  'cross_check_status',
  'cross_check_date',
  'created_at',
];

export const ALLOWED_FIELDS_TO_CREATE = [
  // 'id',
  'order_id',
  'phone_number',
  'product_name',
  'product_type',
  'package_register_type',
  'order_status',
  'provider',
  'total_price',
  'commission_agent',
  'commission_sub_agent',
  'agent_id',
  'sub_agent_id',
  'date',
  'success_date',
  'cross_check_id',
  'cross_check_status',
  'cross_check_date',
  // 'created_at',
];
