export const ALLOWED_TRANSACTION_FIELDS_TO_UPDATE = [
  // 'id',
  // 'orderId',
  'phoneNumber',
  'productName',
  'productType',
  'packageRegisterType',
  'orderStatus',
  'provider',
  'totalPrice',
  'commissionAgent',
  'commissionSubAgent',
  'agentId',
  'subAgentId',
  // 'date',
  'successDate',
  'crossCheckId',
  'crossCheckStatus',
  'crossCheckDate',
  'createdAt',
];

export const ALLOWED_TRANSACTION_FIELDS_TO_CREATE = [
  // 'id',
  'orderId',
  'phoneNumber',
  'productName',
  'productType',
  'packageRegisterType',
  'orderStatus',
  'provider',
  'totalPrice',
  'commissionAgent',
  'commissionSubAgent',
  'agentId',
  'subAgentId',
  'date',
  'successDate',
  'crossCheckId',
  'crossCheckStatus',
  'crossCheckDate',
  // 'createdAt',
];
